### ISSUE TITLE
Searching for more images goes on indefinitely

### ISSUE THREAD

**Issue by devster31** [xbmc/chorus2#309] opened 2017-12-03 23:29 UTC
When trying to change the poster or the background images the page just keeps on loading forever without showing any new images.
Here a screenshot of the issue.
![https://snag.gy/yA60nE.jpg](https://snag.gy/yA60nE.jpg)
Which information are needed to debug this?

**Comment by planet** [comment] 2017-12-04 06:22
i see the same issue

**Comment by LubikR** [comment] 2018-01-14 21:43
It seems that the problem is old TMDB API key - fixed in #313

**Comment by devster31** [comment] 2018-01-14 23:28
I changed the key manually and it seems to work.

**Comment by devster31** [comment] 2018-06-05 14:10
Is there any news about having this in master?

**Comment by jez500** [comment] 2018-07-28 01:46
Fixed default key, and you can add your own API keys via settings if you want
https://github.com/xbmc/chorus2/releases/tag/17.x-2.4.5

**Closed by jez500** 2018-07-28 01:46 UTC
