### ISSUE TITLE
HTML artifacts in displaying album year

### ISSUE THREAD

**Issue by erewhon-smith** [xbmc/chorus2#395] opened 2020-03-28 15:17 UTC
## Expected Behavior

Should display album year under album title in view of an artist's albums.

## Actual Behavior

Shows

"<a href="#music/albums?year=1994"

in place of album year "1994".

## Environment
 - Used browser: Chromium from Arch Linux
 - Operating system running Kodi: Raspbian Buster
 - Kodi version and platform: Kodi 18.5

**Comment by kikendo** [comment] 2020-04-21 12:53
Yup I have the same issue.

**Comment by arigit** [comment] 2020-08-01 20:13
+1, still present on kodi 18.8

**Comment by arigit** [comment] 2020-08-01 20:17
actually this is a duplicate of #358

**Comment by arigit** [comment] 2020-12-17 20:50
Thanks @nagubal!

**Comment by arigit** [comment] 2021-05-07 00:03
@erewhon-smith  the fix for this has been merged in master and will be included in the next release (20.x). This issue can be closed now.

**Closed** 2021-05-07 08:19 UTC

**Comment by enen92** [comment] 2021-05-07 08:21
It will be included in v19.1 of Kodi which is about to be released (and also in v20 if the default webinterface is not replaced ) . Thanks for the fixes.
