### ISSUE TITLE
Feature request: activate and change subtitles in the player

### ISSUE THREAD

**Issue by Boilerplate4u** [xbmc/chorus2#450] opened 2021-11-16 18:50 UTC
--
Please add the ability activate and choose subtitles in the player (using for example json Player.SetSubtitle, Player.Subtitle, etc)
--

Thanks in advance! :-D

*Note: Team Kodi will consider this item however we will not make any promises if it will be included.*

**Comment by malard** [comment] 2024-01-27 22:06
dupe of #175

**Closed by malard** 2024-01-27 22:06 UTC
