### ISSUE TITLE
[Feature Request] Set Kodi system date and time from time on current device

### ISSUE THREAD

**Issue by mrwish7** [xbmc/chorus2#561] opened 2024-01-09 10:02 UTC
## Feature suggestion
Add a button/link to update the date and time on the machine running Kodi, to the time on the current device that's browsing the Chorus interface.

### Context

I'm running LibreElec on a Raspberry Pi 4, with LibreElec wireless access point configured. This means that when travelling, I can start up the Pi and connect wirelessly via my laptop or phone to control the system. I'm using TVHeadend with the TV hat to tune DVB-T2 signals. The problem that happens with this set-up is that the Pi is not connected to the internet, so the date and time are not accurately set on boot, and this breaks TVHeadend recordings as these use the system time for timers.

I've been getting around this by changing the timezone in Chorus to the correct one for my location at the time, then running the following command in SSH to force the time -

`date -s "YYYY-MM-DD HH:MM:SS"`

This has to be done every time I boot the system. 

### Possible Implementation

What would be really helpful would be to have a button, maybe next to the timezone settings in Chorus, that sends a date/time update to the system based on the current device's time. I'm guessing this would require that we can set the system time via the Kodi API? I'm guessing this would be possible because it's already possible to change the actual timezone, but maybe it would need more thought.

Could this even be automated so that if it's noticed that the time/date on the current system and the time/date on the system running Kodi/Chorus are different, there's a prompt to sync and update?

**Comment by basilgello** [comment] 2024-01-09 11:37
No need to mess with Kodi core here. Internal representation of PVR data is everywhere as UTC (at least in cdatetime-std-chrono branch I did that explicitly), so once it gets merged, only a Chrorus PR might be needed to apply browser's timezone bias.

**Comment by malard** [comment] 2024-01-27 21:25
basically a dupe of #560

**Closed by malard** 2024-01-27 21:25 UTC
