### ISSUE TITLE
Overylay Screen when play from playlist

### ISSUE THREAD

**Issue by robsee** [xbmc/chorus2#204] opened 2017-01-08 18:23 UTC
Hi, 
When I choose to play something from the playlist in the webinterface, It leaves the menu/overlay screen up with the media underneath (on the Kodi display). I then have to go to the menu and hit the back button to get it to go to the full screen media.

**Comment by jez500** [comment] 2017-01-09 07:57
Hey,
So this is a bug with the API, specifically http://kodi.wiki/view/JSON-RPC_API/v6#Player.Open
When you open (play) an item in the video playlist, it opens the overlay... annoying
I tested this with the [Kore remote](https://play.google.com/store/apps/details?id=org.xbmc.kore&hl=en) and the same thing happens

**Comment by robsee** [comment] 2017-01-09 13:19
Could it be worked around by making a "go to fullscreen" api call right after a change in the media ?

**Comment by jez500** [comment] 2017-01-10 09:30
I'm not a fan of that idea because if someday it gets fixed in the API, then that will reverse the fix (because you call fullscreen toggle). That said I'll have a play, there might be a workaround somewhere

**Comment by malard** [comment] 2024-01-27 22:25
not a bug with chorus

**Closed by malard** 2024-01-27 22:25 UTC
Labels: API Issue
